name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: resolving dependencies 1
      run: git submodule update
    - name: resolving dependencies 2
      run: git submodule init
    - name: cmake_gen
      run: cmake .
    - name: cmake_build
      run: cmake --build .
    - name: moving_dependencies
      run: Move-Item -Path dep\runtime\* -Destination Debug\
    - name: run_app
      run: "Debug/armasimu"
