name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: build_and_run
      run: build_and_run.bat
    - name: cmake_gen
      run: cmake .
    - name: cmake_build
      run: cmake --build .
